from .TeaCache_Coefficient_Calculator import (
    NODE_CLASS_MAPPINGS as CALC_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CALC_NODE_DISPLAY_NAME_MAPPINGS,
)

from .TeaCache_Lumina2 import (
    NODE_CLASS_MAPPINGS as LUMINA2_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LUMINA2_NODE_DISPLAY_NAME_MAPPINGS,
)

# Merge all node mappings
NODE_CLASS_MAPPINGS = {
    **CALC_NODE_CLASS_MAPPINGS,
    **LUMINA2_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **CALC_NODE_DISPLAY_NAME_MAPPINGS,
    **LUMINA2_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
