from .TeaCache_Coefficient_Calculator import (
    NODE_CLASS_MAPPINGS as CALC_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CALC_NODE_DISPLAY_NAME_MAPPINGS,
)

from .TeaCache_Newbie import (
    NODE_CLASS_MAPPINGS as NEWBIE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as NEWBIE_NODE_DISPLAY_NAME_MAPPINGS,
)

# Merge all node mappings
NODE_CLASS_MAPPINGS = {
    **CALC_NODE_CLASS_MAPPINGS,
    **NEWBIE_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **CALC_NODE_DISPLAY_NAME_MAPPINGS,
    **NEWBIE_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
